name: GitHub Actions CI

on:
  push:
    branches: [main, 42-write-xunit-tests]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"
  pull_request:
    branches: [develop]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.sln"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" \
          --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/TestResults/*.trx"

